# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x07\n\x05\x45mpty\"C\n\rSimpleMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"7\n\x0cStateMessage\x12\x16\n\x06status\x18\x01 \x01(\x0e\x32\x06.state\x12\x0f\n\x07message\x18\x02 \x01(\t**\n\x05state\x12\x06\n\x02OK\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\x0c\n\x08\x43RITICAL\x10\x02\x32\x64\n\x0eMessageService\x12,\n\x0bSendMessage\x12\x0e.SimpleMessage\x1a\r.StateMessage\x12$\n\x0bHealthCheck\x12\x06.Empty\x1a\r.StateMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATE']._serialized_start=152
  _globals['_STATE']._serialized_end=194
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_SIMPLEMESSAGE']._serialized_start=26
  _globals['_SIMPLEMESSAGE']._serialized_end=93
  _globals['_STATEMESSAGE']._serialized_start=95
  _globals['_STATEMESSAGE']._serialized_end=150
  _globals['_MESSAGESERVICE']._serialized_start=196
  _globals['_MESSAGESERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
